### ISSUE TITLE
Groonga command column_rename is not supported

### ISSUE THREAD

**Issue by okkez** [ranguba/groonga-client-model#2]
Groonga command `column_rename` is not supported.

Is there any problem to support `column_rename` command?

**Comment by kou** [comment]
Generally, no.

BTW, where do you want to use `column_rename`? In migration? If you want to use in migration, we should not export `column_rename` directly. We should use Active Record like name for consistency.

**Comment by okkez** [comment]
Thank you for response.

I want to use `column_rename` in migration.
At this time, I've used `column_rename` command via groonga-client and edit migration file directly.

**Comment by kou** [comment]
It'll be better that we define `#rename_column` in https://github.com/ranguba/groonga-client-model/blob/master/lib/groonga_client_model/migration.rb

**Comment by kou** [comment]
`#rename_column` has been implemented.
