### ISSUE TITLE
A lot of test data making the new release really big

### ISSUE THREAD

**Issue by mensfeld** [ranguba/groonga-client-model#6]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for Ruby libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that the tests directory is added to it. Usually, that's quite ok but in your case, it eats up over 150MB of space when uncompressed and makes it really hard to track changes in between releases. 

Not sure if you will consider this as an error or not but just wanted to make you aware of this.

Have a great day.

**Comment by kou** [comment]
Thanks for notifying this.
We should have not add auto generatable files to gem.

**Comment by mensfeld** [comment]
You are welcome. Thank you for addressing this so fast! I will keep an eye on this in the future :pray:  :)
